#:schema node_modules/wrangler/config-schema.json
name = "cohive-cloudflare"
main = "functions/api/[[route]].ts"
compatibility_date = "2026-07-01"

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "cohive_db"
migrations_dir = "./migrations"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "cohive-storage"

[vars]
ENVIRONMENT = "production"
SAAS_MODE = "true"

[[ratelimits]]
name = "RATE_LIMITER"
namespace_id = "1002"

[ratelimits.simple]
limit = 20
period = 60
