#:schema node_modules/wrangler/config-schema.json
name = "cohive-saas"
compatibility_date = "2026-07-02"

[assets]
directory = "./dist"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "cohive_saas_db"
migrations_dir = "./migrations"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "cohive-saas-storage"

[vars]
ENVIRONMENT = "production"
SAAS_MODE = "true"

[[ratelimits]]
name = "RATE_LIMITER"
namespace_id = "1002"

[ratelimits.simple]
limit = 20
period = 60
